mirage/ocaml-qcow

cli/impl.ml, cli/main.ml, lib/qcow.ml, lib/qcow.mli, lib/qcow_s.mli, lib/qcow_virtual.ml, lib/qcow_virtual.mli, lib_test/test.ml
This includes tests which write at "interesting" locations in the image (e.g. just before a cluster boundary, just after a cluster boundary etc) and then iterates over the data in the image to check it is correct.
=> Add lots of boundary tests

cli/main.ml, lib_test/test.ml
For example:
```
./main.native create test.qcow2 --size 16GiB
```
=> CLI: parse/print sizes nicely (KiB, MiB, GiB, TiB, PiB)

CHANGES.md, README.md
=> Add CHANGES.md; update README.md

Makefile, opam
=> Install and uninstall qcow-tool

CHANGES.md, README.md, _oasis
=> Bump version to 0.2

CHANGES.md, _oasis
=> Prepare to release v0.4.2

CHANGES.md, cli/impl.ml, cli/main.ml, lib/qcow.ml, lib/qcow.mli, lib_test/test.ml
- improve (but change) the `resize` API
- add simple tests for resize
- add `resize` to the CLI
- fix a bug in the implementation
Fixes #21
=> Add resize support

CHANGES.md, _oasis, opam
=> Prepare to release v0.5.0

lib/qcow.ml, lib/qcow.mli
This currently has a single field
- `discard`: whether `discard` is considered enable and working.
This is expected to be plumbed through to the client via the
appropriate capability query mechanism.
=> Add a Config.t for runtime options

lib_test/test.ml
=> test: add tests for discarding all blocks

lib_test/compact_random.ml
=> test: include cancellation in the random operations test

lib/qcow.ml
Previously a corrupt image may be `connect`-able but later calls to `read` or `write` might fail. This patch makes `connect` call `check` which will cause the `connect` to fail if the image is obviously
corrupt.
This will make `connect` slightly slower, but it will cause the metadata blocks to be cached speeding up future I/O.
=> connect: call `check` to sanity-check the image

CHANGES.md, pkg/META
=> Prepare to release v0.7.0

CHANGES.md, pkg/META
=> Prepare to release v0.7.1

CHANGES.md, pkg/META
=> Prepare to release v0.7.2

.travis.yml, README.md, _tags, cli/impl.ml, cli/main.ml, lib/qcow.ml, lib/qcow.mli, lib/qcow_cluster_map.ml, lib/qcow_cluster_map.mli, lib/qcow_s.ml, lib/qcow_s.mli, lib/qcow_timer.ml, lib/qcow_timer.mli, lib_test/compact_random.ml, lib_test/error.ml, lib_test/error.mli, lib_test/qemu.ml, lib_test/qemu.mli, lib_test/sizes.ml, lib_test/test.ml, lib_test/utils.ml, opam, pkg/META
Master has been temporarily moved back to the old APIs for further development and releases before the Mirage 3 release.
This is equivalent to #27.
=> Update to Mirage 3 APIs

CHANGES.md, pkg/META
=> Prepare to release v0.8.0

pkg/META
=> META: fix package names (mirage-foo.lwt -> mirage-foo-lwt)

CHANGES.md, pkg/META
=> Prepare to release v0.8.1

CHANGES.md, pkg/META
=> Prepare to release v0.9.0

CHANGES.md
=> Prepare to release v0.9.2

lib/qcow.ml
During a read or write operation, we look up the L1, then the L2, then finally the data cluster. Sometimes we will need to allocate the data cluster and write to the L2. Holding the read
lock on the L1 prevents a background compact from moving the L2 cluster while we're about to write the new data reference to it.
This patch causes read and write to maintain read locks on the required L1 and L2 clusters during the operation.
=> Hold a read lock on the L1 table entry

CHANGES.md
=> Prepare to release v0.9.3

lib/qcow.ml, lib/qcow_cluster_map.ml, lib/qcow_cluster_map.mli, lib/qcow_recycler.ml, lib/qcow_recycler.mli
This attempts to make the currently low-level Junk/Available/Erased/Copies interface a bit higher level and adds more sanity checks.
=> Add more sanity checks

CHANGES.md
=> Prepare to release 0.9.4

CHANGES.md
=> Prepare to release v0.9.5

lib/qcow_cluster_map.ml
=> prometheus: decrement `used` when removing a reference

qcow-tool.opam, qcow.opam
see also https://github.com/ocaml/opam-repository/pull/8757 for
fixes to older releases
=> opam: update constraints, remove duplicates

CHANGES.md
=> Prepare to release 0.10.1

CHANGES.md, cli/jbuild, lib/jbuild, qcow-tool.opam, qcow.opam
- prepare to release a minor update
- remove package name from build rules
=> Remove spurious cmdliner dependency

CHANGES.md, cli/impl.ml, qcow-tool.opam
=> Update to OCaml 4.06 (and -safe-string)

CHANGES.md
=> Prepare to release v0.10.5

lib/qcow.ml, lib/qcow_cluster_map.ml
=> Remove dead code

LICENSE.md
Note: This is part of a series of PRs submitted to repos in the mirage organization, along the lines of mirage/jitsu#36 (2016), mirage/irmin#472 (2017) and mirage/mirage#905 (2018).
=> LICENSE.md: add title and copyright year range

.circleci/config.yml
=> circleci: remove macos (requires a paid plan)

.circleci/config.yml
=> circleci: build in a docker image

.circleci/config.yml, .dockerignore, Dockerfile, qcow-tool.opam, qcow.opam
=> circleci: use docker so we can test things locally

cli/main.ml, lib/qcow.ml, lib/qcow_header.ml
On top of #123, so only the last three commits are specific to this PR.
=> Further fixes: parsing, CLI, overallocation

dune-project, qcow-stream.opam, qcow-types.opam
These were found by the CI at https://github.com/ocaml/opam-repository/pull/27978
=> opam: add more lower bounds to dependencies
