lib/qcow.ml
lib_test/test.ml

`read` and `write` now
- operate in cluster-sized and cluster-aligned chunks where possible
- submit physical I/O in parallel

Improve performance and alignment

---

lib/qcow.ml

Without this, parallel allocation requests can overlap such that the
earlier (smaller) `ftruncate` can be completed after the later (larger)
one, chopping off a cluster that has just been allocated.

Protect cluster allocation with a mutex

---

cli/impl.ml
cli/main.ml
lib/qcow.ml
lib/qcow.mli

`qemu-img` seems to "allocate" the final cluster in a file by writing
a single sector only. Cope with this by:
- on every `read`, check if we're in this last-cluster situation and
synthesize zeroes for missing sectors
- on `connect`, round up to the next cluster size when setting the
`next_cluster` pointer.
With this patch, a `qemu-img` generated .qcow2 seems to work ok with
this code as measured by the CLI `check` subcommand.

Cope with files which are not whole numbers of clusters

---

cli/impl.ml
cli/main.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow_s.mli
lib_test/test.ml

- Fix an infinite loop when enlarging the refcount table
- add CLI commands `read` and `write`

Fix infinite loop enlarging the refcount table

---

Makefile
lib/qcow.ml
lib/qcow_header.ml
lib/qcow_header.mli
lib/qcow_physical.ml
lib/qcow_physical.mli
lib/qcow_types.mli
lib/qcow_virtual.ml
lib/qcow_virtual.mli
lib_test/test.ml

This patch also adds a target `make reindent`

Reindent with ocp-indent

---

.travis.yml
_oasis
lib/qcow.ml
lib/qcow_header.ml
lib/qcow_header.mli
lib_test/error.ml
lib_test/error.mli
lib_test/extent.ml
lib_test/qemu.ml
lib_test/qemu.mli
lib_test/sizes.ml
lib_test/test.ml
lib_test/utils.ml
opam

We wish to ensure this library is compatible with qemu. These patches add some testing wrappers around qemu commands which we'll exploit in future patches.

Add simple wrappers around qemu commands for tests

---

.travis.yml
CHANGES.md
_oasis
lib/qcow_header.ml
lib/qcow_header.mli
lib/qcow_physical.ml
lib/qcow_physical.mli
lib/qcow_types.ml
lib/qcow_types.mli
lib/qcow_virtual.ml
lib/qcow_virtual.mli
lib_test/extent.ml
opam

- use `ppx_sexp_conv` rather than `sexplib.syntax`
- bump version to 0.3
Fixes #18 (although now will need a fairly new sexplib)

Use ppx rather than camlp4

---

CHANGES.md
_oasis
cli/impl.ml
cli/main.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow_header.ml
lib/qcow_header.mli
lib/qcow_s.mli
lib_test/qemu.ml
lib_test/qemu.mli
lib_test/test.ml
opam

We now require a `BLOCK` device which includes a `flush` function which we will call at key points to ensure qcow metadata is persisted. Note it is still the user's responsibility to call `flush` to persist user data in this case.
When lazy refcounting is requested (the default) we do not maintain refcount tables at all. Running `qemu-img check` will highlight the missing refcounts. The `qcow-tool repair` command will rebuild the refcount tables such that `qemu-img check` will be happy.
This PR also fixes bugs in the `seek_mapped` function, highlighted by its use in `repair`.
Prepare to release v0.4

Flush and use lazy refcounts properly

---

CHANGES.md
_oasis
cli/impl.ml
cli/main.ml
lib/qcow.ml

We don't need to flush after every allocation since if any of the writes are dropped, it will be as if the allocation never happened (modulo the size of the file)

Remove an unnecessary call to flush

---

cli/impl.ml

See [mirage/mirage-block-unix#52]

CLI: don't break the build if Block.connect has optional arguments

---

.travis.yml
README.md
cli/impl.ml
lib/qcow.ml
lib/qcow.mli
lib_test/qemu.ml
lib_test/qemu.mli
lib_test/test.ml

needs https://github.com/xapi-project/nbd/pull/28
tests run on my laptop... but I've no clue about this library, code review would be appreciated.
I also modified in lib_test Qemu.create to return `t io` instead of `(`Ok t) io`, there are likely more return types which can be adjusted (not sure why connect calls read, and I've to handle these errors manually, but previously it also failed hard if an error occured; maybe connect should call some read_internal which doesn't return an ``Error`).

connect no longer returns a result type

---

lib_test/test.ml

- re-enable some tests which were disabled by accident
- check that "create x; resize y" yields the same data on-disk as "create y"

Add more resize tests

---

cli/impl.ml
cli/main.ml

This makes it easier to query qcow2 header metadata from scripts. For example:
```
$ qcow-tool info 1K.qcow2 --filter .additional.[0].dirty
true
$ qcow-tool info 1K.qcow2 --filter .size
1024
```

Add a --filter argument to info

---

_oasis
cli/common.ml
cli/impl.ml
cli/main.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow_diet.ml
lib/qcow_diet.mli
lib/qcow_physical.ml
lib_test/compact_random.ml
lib_test/test.ml
lib_test/utils.ml

This PR adds support for a `discard` operation which marks a range of sectors as empty. The implementation guarantees "Read Zero After TRIM" semantics.
Space is not reclaimed immediately (yet), instead a special `compact` operation scans across all the metadata and shuffles blocks from the end of the file into holes near the start and updates any references to match. This should be run offline periodically and will truncate the file to make it smaller.
Two new CLI sub-commands have been added
- `discard`: scans the file for zeroes and calls `discard` on the blocks
- `compact`: runs the compactor and shrinks the file
For example
```
$ qcow-tool compact Docker.qcow2
I couldn't make the file any smaller. Consider running `discard`.
$ qcow-tool discard Docker.qcow2
$ qcow-tool compact …
```

Add support for `discard` aka TRIM

---

lib/qcow.ml

The highest still allocated block can be arbitrarily lower than
the next_cluster in cases where the last blocks have been discarded.

compact: remove an erroneous assert

---

lib/qcow.ml
lib/qcow.mli

- avoid filling blocks with zeroes in edge cases by checking whether the cluster is mapped
- add a read/write lock to protect global metadata for whole-file changing operations
- add a `compact_after_unmaps` configuration option which requests an automatic (blocking) compaction every n deallocated sectors

Further TRIM/discard improvements

---

lib/qcow.ml
lib/qcow_diet.ml
lib/qcow_diet.mli
lib_test/compact_random.ml

- fix critical bug where we would `discard` more sectors than we were asked to
- improve the random operations `discard`/`compact` test case

Improve discard tests, fix bug

---

lib/qcow_diet.ml
lib_test/compact_random.ml

The test case now writes sector-aligned rather than cluster-aligned data to test the edge case handling.
The interval tree now checks a critical invariant in `add` and `remove` and will raise `Invalid_argument`

Improve the random test case

---

cli/impl.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow_diet.ml
lib/qcow_diet.mli
lib_test/compact_random.ml

- make `interval` abstract so we can't skip checking the invariant
- check that all cluster references are within the file
- check that no cluster has two references

Add more sanity checks

---

cli/impl.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow.mllib
lib/qcow_rwlock.ml
lib/qcow_rwlock.mli
lib/qcow_timer.ml
lib/qcow_timer.mli
lib_test/compact_random.ml
lib_test/test.ml
lib_test/utils.ml

Previously if we had a configured auto-compaction threshold then we would perform the compact synchronously in a discard. This meant that
- `discard` could block for a long time
- if discarding a lot, we could waste time shuffling blocks that we're about to delete
This PR (re-)starts a timer on every discard over the threshold and only triggers the compact if there have been no discards for 1s.
Note this functorises `Qcow` over `V1_LWT.TIME`

Decouple discard from compact

---

lib/qcow.ml
lib/qcow.mllib
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_diet.ml
lib/qcow_diet.mli
lib/qcow_s.ml
lib/qcow_s.mli
lib/qcow_timer.ml
lib/qcow_timer.mli

Clients like Linux become upset if I/O is blocked for too long -- for Linux this seems to be more than 30s. This PR makes the `compact` operation safely cancellable and modifies `read` `write` and `discard` to cancel any in-progress `compact`. If a `compact` is cancelled, it is rescheduled for 1s in the future.

Interrupt the background compact, rather than block I/O

---

lib/qcow.ml
lib/qcow.mli

Currently it will auto-compact after 1s but this can be changed by the
new `compact_ms` configuration parameter.

Make the auto-compaction timer configurable

---

_tags
cli/impl.ml
cli/main.ml
lib/qcow.ml
lib/qcow.mllib
lib/qcow_bitmap.ml
lib/qcow_bitmap.mli
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_diet.ml
lib/qcow_error.ml
lib/qcow_header.ml
lib/qcow_header.mli
lib/qcow_physical.ml
lib_test/compact_random.ml
lib_test/extent.ml
lib_test/qemu.ml
lib_test/sizes.ml
lib_test/test.ml

Previously we used an interval tree but this seems to be pathological when the file is not very sparse. When running `qcow-tool check` on a 42GiB non-sparse file, the runtime drops from ~50s to ~1.2s.

Use a bitmap for free block tracking

---

_tags
lib/qcow.ml
lib_test/compact_random.ml
lib_test/test.ml

This PR avoids the clash between refcounts and TRIM/discard/compact by forcibly disabling refcounts when the `discard` configuration option is requested.
- if `discard` is requested, enable `lazy_refcounts` and zero existing refcounts
- if `discard` is performed but the `discard` feature is turned off, return an error
Fixes #56

Decrement refcounts

---

lib/qcow_diet.ml

Previously some usage patterns could result in extremely unbalanced interval trees, making operations like `mem` linear in the number of intervals. This PR keeps the tree balanced so these worst case operations go from `linear` to `log_2`.

Keep the interval tree balanced

---

cli/impl.ml
lib/qcow.ml
lib/qcow.mli

Previously `qcow-tool check` would fail if blocks were being concurrently allocated because we would find pointers outside the file. This PR enhances the error types from `connect` and `check` to describe this situation and makes `qcow-tool check` run up to 5 iterations attempting to get a consistent picture of the file. If `qcow-tool check` detects real damage, it always fails. If it detects a pointer outside the file which is actually now inside the file (due to expansion) it repeats up to 5 times.
For example
```
main.native: [ERROR] Found a reference to cluster 107384 outside the file (max cluster 107383) from cluster 105855.12016
main.native: [ERROR] Found a reference to cluster 108409 outside the file (max cluster 108408) from cluster 105855.20216
main.native: [ERROR] Found a …
```

check: cope with concurrent file modification

---

lib/qcow.ml
lib/qcow.mli
lib/qcow_recycler.ml

- catch the exception properly in `check` (previously it would escape to the top-level)
- ensure `compact` runs enough iterations (2 may be needed, 3 is a sanity-check)
- fix the calculation of the number of updated blocks

Misc fixes

---

.travis.yml
CHANGES.md
lib/qcow.ml
lib/qcow.mli
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_config.ml
lib/qcow_config.mli
lib/qcow_locks.ml
lib/qcow_locks.mli
lib/qcow_metadata.ml
lib/qcow_metadata.mli
lib/qcow_recycler.ml
lib/qcow_recycler.mli
lib/qcow_rwlock.ml
lib/qcow_rwlock.mli
lib/qcow_s.ml
lib/qcow_s.mli
lib_test/compact_random.ml
lib_test/test.ml
pkg/pkg.ml

Previously the read/writer cluster locks were non-recursive, but this
was awkward because we wanted to take a batch of reads/writes, lock
all the metadata clusters for reading, acquire a write lock too if
necessary where some of the metadata clusters are shared.
This patch makes the locks optionally recursive: a `client` owns a set
of locks and can acquire the same lock it already has.
This patch also includes a test case which verifies that a compact
in the middle of a `write`, (a) doesn't deadlock; and (b) doesn't lose
data.

Make the cluster locks recursive

---

lib/qcow.ml
lib/qcow_locks.ml
lib/qcow_locks.mli
lib/qcow_recycler.ml

Previously the `update_references` function (responsible for updating the pointers to moved clusters to point to the new location) would hold the global "metadata" lock (really the allocation + file size lock) for the whole operation. This can be removed altogether as the `read`/`write` threads maintain a fine-grained read lock on the relevant metadata block instead. Hopefully this avoids blocking the I/O for too long.
Since clients like Linux AHCI driver don't like blocking for more than 30s this PR also adds a timer around `read`, `write` and `discard` which will log the state of locks if this timeout condition occurs.

Remove one more use of global lock

---

lib/qcow.ml
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_int64.ml
lib/qcow_int64.mli
lib/qcow_metadata.ml
lib/qcow_metadata.mli
lib/qcow_recycler.ml
lib/qcow_recycler.mli

Previously we would iterate over all data clusters to be discarded and set the L2 pointer to 0. Unfortunately this means we would often update and write out the same L2 cluster many times, if discarding many data clusters.
This patch holds the write lock on the L2 cluster and updates all the relevant pointers before flushing it out, exactly once.

Increase discard performance

---

lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_recycler.ml

- Previously we would update references in an arbitrary order, locking and unlocking clusters as we go. It's likely that many of the references are in the same clusters so we should try to minimise the amount of lock/unlock thrashing.
- Update the `t.Qcow_cluster_map.refs` in `update_references`: normally this is done by construction through `Metadata.Physical.set` but while compacting we deliberately copy the cluster at the byte level leaving the old reference intact-- we only update the reference when the copy has been flushed to disk
- Construct and apply a cluster substitution map as we `fold_left` in `update_references`: this ensures that if we move a block containing references and then move a block referenced by this block, we update the reference in the new block rather than the …

Fix updating references

---

lib/qcow.ml
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli

We will use this in a later test to verify that the cluster map we construct from scratch equals the one we have maintained dynamically.

Add an `assert_equal` for Qcow_cluster_map

---

lib/qcow.ml
lib/qcow_cluster_map.ml
lib/qcow_s.ml
lib/qcow_s.mli
lib_test/compact_random.ml
lib_test/test.ml

This calls `assert_cluster_map_in_sync` from a few tests where it might have gotten out-of-sync.

test that the cluster reference map remains in sync

---

lib/qcow.ml
lib/qcow_cluster_map.ml
lib/qcow_recycler.ml

- illegal state transitions will now trigger an `assert`
- avoid starting 2 possibly conflicting block moves at once by waiting for the previous one to complete first

Strictly enforce the cluster state machine

---

lib/qcow.ml
lib/qcow.mli
lib/qcow.mllib
lib/qcow_cache.ml
lib/qcow_cache.mli
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_debug.ml
lib/qcow_debug.mli
lib/qcow_error.ml
lib/qcow_error.mli
lib/qcow_locks.ml
lib/qcow_recycler.ml
lib/qcow_rwlock.ml
lib/qcow_rwlock.mli

Previously at runtime we would `assert false` which didn't help debugging much. This patch will perform some analysis and look for a discrepancy between the references on disk and the references in the map.

Improve the error reporting when we encounter a duplicate reference

---

lib/qcow.ml
lib/qcow.mli

The default value is 16 i.e. 64KiB clusters. This PR adds the ability to request a different value at `connect` time. For the moment this is mainly useful for testing, as using a lower value will stress the metadata handling more.

Allow cluster_bits to be overridden

---

cli/impl.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow_config.ml
lib/qcow_config.mli

Previously the standard `connect` function would perform some housekeeping e.g. it would resize the block device to remove any trailing junk. Unfortunately these modifications could conflict with another process which has the file open for writing. In particular we wish to allow `check` on live files.
This PR adds a runtime configuration parameter `read_only` which promises to not resize or otherwise modify the file. This PR also adds a "read-only" virtual block device which is used by the CLI `check` and `sha` to abort the program if `write` or `resize` is called.
Fixes #84

CLI commands `check` and `sha` must not modify the file

---

circle.yml

In Docker for Mac, we package qcow-tool ourself. It will be better to compile it in a proper build. 
This is the first step for getting this artifact. 
For the libev dependency, I don't really know what should I do. I tried a lot of things to get the dylib compiled with the correct flags without luck. Can I get help on this ? Thanks!

Add circleci build

---

.gitignore
.travis.yml
Makefile
cli/jbuild
generator/gen.ml
generator/jbuild
lib/jbuild
lib_test/jbuild
qcow-tool.opam
qcow.opam

This is based on samoht/bew. To use:
opam pin add jbuilder --dev
make -f Makefile.experimental
Building everything with ocamlbuild takes ~9.4s
Building everything with jbuilder takes ~2.3s

Add experimental support for jbuilder

---

cli/impl.ml
cli/jbuild
cli/main.ml
lib/qcow.ml
lib/qcow.mli
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_s.ml
lib/qcow_s.mli

When debugging problems in the field, we need to analyse very large files. It isn't reasonable to expect someone to email us 100 GiB of their personal data: we need something safer and smaller.
This PR adds 2 new CLI commands:
- `qcow-tool dehydrate input.qcow2 output`: creates 2 files: `output.map` describing the metadata blocks and `output.meta` containing the metadata blocks. Crucially no user data is included.
- `qcow-tool rehydrate output output.qcow2`: consumes the 2 files created above and creates a new `output.qcow2` file with the same metadata structure as `input.qcow2` but where all the data blocks contain zeroes.

Add CLI commands "dehydrate" and "rehydrate"

---

lib/jbuild
lib/qcow.ml
lib/qcow.mli
lib/qcow_cluster_map.ml
lib/qcow_cluster_map.mli
lib/qcow_config.ml
lib/qcow_config.mli
lib/qcow_types.mli
lib_test/test.ml
qcow.opam

This exposes metrics for each of the categories of clusters tracked by the garbage collector:
- `used`: a Gauge counting the number of bytes of user data
- `size`: a Gauge counting the number of bytes in the file
- `junk`: a Counter counting the number of bytes which become junk
- `erased`: a Counter counting the number of bytes which are erased
- `available`: a Counter counting the number of bytes which become available for reallocation
- `roots`: a Counter counting the number of bytes registered as roots
- `copying`: a Counter counting the number of copies started
- `copied`: a Counter counting the number of copies completed
- `flushed`: a Counter counting the number of bytes flushed
- `referenced`: a Counter counting the number of bytes re-referenced
and general I/O metrics:
- `reads`: …

Add prometheus metrics

---

lib/qcow.ml
lib/qcow_recycler.ml
lib/qcow_recycler.mli

In a recent refactor the `progress_cb` was removed. This patch adds
it back in, with the convention that the first pass (copying data blocks)
will constitute the (arbitrary) first 80% of progress, while the second
pass (rewriting references and copying metadata blocks) constitutes
the last 20%.

compact: hook back up the progress_cb

---

lib/qcow_diet.ml

The IntervalSet `union` is roughly:
```
let union a b = fold add a b
```
where elements of `a` are added to `b`. Therefore if one of the
sets is much smaller than the other we should make it the 1st
argument.
Running a `qcow-tool compact` on files created with
`qcow-tool pattern --pattern 2` shows the following speedup:
```
Size/GiB      Before/seconds    After/seconds
1             20                1
2             87                3
8             1369              15
16            ??                25
64            ??                139
```

perf: make interval union calculations faster

---

cli/common.ml
cli/impl.ml
cli/jbuild
cli/main.ml
qcow-tool.opam

If selected, this will write json-formatted progress records like this:
`{ "progress": 50 }`
to the given file descriptor.

cli: compact: add --progress-fd <file descriptor>

---

.travis.yml
lib/jbuild
pkg/META
pkg/pkg.ml
qcow.opam

- the library currently needs `io-page` but only the CLI needs `io-page-unix`
- refresh `topkg` configuration

Only qcow-tool needs io-page-unix

---

doc/dashboard.json
doc/prometheus.md
doc/prometheus.yml

This describes how to turn the metrics on, how to scrape them and how to render them into a dashboard.
Fixes #99

Document the prometheus metrics support

---

cli/impl.ml
qcow-tool.opam

All of the operations require the disk to be locked exclusively except
- `info` which reads the header using the low-level API
- `check` which is designed to cope with the disk being modified concurrently
This PR also renames `Block` to `ReadWriteBlock` and uses `ReadOnlyBlock` in more places.

cli: use new mirage-block-unix locking feature
